P=gsl_erf
OBJECTS=
CFLAGS=`pkg-config --cflags glib-2.0` -g -std=c11 -Wall -O3
LDLIBS=`pkg-config --libs gsl glib-2.0`
CC=gcc

$(P): $(OBJECTS)

fib:

parith:

macro:

file1:

constchange:

check_name:

constfusion:

str:

compound:

show_tree: process_dir.o

charct: process_dir.o unictr.o
